name: وبلاگ پاسگاه؛ بیوگرافی افراد مشهور

description: وبلاگ پاسگاه؛ بیوگرافی افراد مشهور. از خاطرات تا دستاوردهای افراد مشهور ایران و جهان

url: https://www.pasgah.org

permalink: /:title

encoding: UTF-8

author:
  name: "احسان چهری"
  email: "ehsanchehri@gmail.com"
  url: "https://www.facebook.com/ehsanchehri"
  bio: "نویسنده وبلاگ پاسگاه"
  avatar: "/biography.svg"
