title: وبلاگ پاسگاه؛ تاریخ و تمدن ایران و جهان

description: وبلاگ پاسگاه با کنجکاوی در تاریخ کشورها سعی می‌کنه شما رو با تاریخ و تمدن ایران و جهان آشنا بکنه و با تاریخ آشتیتون بده!

url: https://www.pasgah.org

permalink: /biography/:title

encoding: UTF-8

timezone: Asia/Tehran
